---
cluster_name: "single-az-k8s"
kubernetes_version: "1.30"
kubernetes_repo_baseurl: "https://pkgs.k8s.io/core:/stable:/v1.30/rpm/"
kubernetes_repo_gpgkey: "https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key"
pod_network_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
flannel_manifest_url: "https://github.com/flannel-io/flannel/releases/download/v0.25.7/kube-flannel.yml"
control_plane_endpoint_port: "6443"
