---
- name: Resolve control plane host
  ansible.builtin.set_fact:
    control_plane_host: "{{ groups['node_type_control_plane'] | first }}"

- name: Ensure worker has a valid control-plane join command
  ansible.builtin.assert:
    that:
      - control_plane_host is defined
      - control_plane_host | length > 0
      - hostvars[control_plane_host].kubeadm_join_command is defined
      - hostvars[control_plane_host].kubeadm_join_command | length > 0
    fail_msg: "Missing kubeadm join command from the control plane run."

- name: Join worker to Kubernetes cluster
  ansible.builtin.command: "{{ hostvars[control_plane_host].kubeadm_join_command }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
